### ISSUE TITLE
Getting rid of the constructor constraint

### ISSUE THREAD

**Issue by Memnarch** [zensan/pascal.today#1]
Currently the Arc<T> is supposed to be a container, but at the same time manages instance creation of the encapsulated Value.

There is no need for the constructing of the value in usual cases (means everything without WITH). 

```
var
  LValue: Arc<TFoo>;
begin
  LValue := TFoo.Create();
end;
```

The implicit operator does the job. Constrained is only usefull for the WITH example, which is considered bad practice.

I'd propose to remove the buildin Instance creation in favour of functionality.

**Comment by zensan** [comment]
Hi!

Thanks for feedback! But mainly I use on my taste and the basis is borrowed
from Marco Cantu book. You are free to make any adjustments. The WITH
examples were just for illustration purposes.

Best regards,
Zigmund.

**Comment by zensan** [comment]
Hi again!

I read your e-mail now on fresh mind (not at midnight). I see your idea and
actually agree. I will incorporate your suggestion as soon as i have time.

Thank you again and sorry that i did not understand you from the first time
at night ;)

**Comment by zensan** [comment]
Fixed in master.

**Comment by Memnarch** [comment]
Cool, and thanks :)
